name: wishlist_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  image_picker: ^1.0.8
  intl: ^0.19.0
  numberpicker: ^2.1.2
  sqflite: ^2.3.3

flutter_native_splash:
  color: "#e0e0e0"
  image: lib/images/splash_icon.png

  android_12:
    image: lib/images/splash_icon.png
    color: "#e0e0e0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/images/splash_icon.png"

flutter:
  uses-material-design: true

  assets:
    - lib/images/
